remote_theme: just-the-docs/just-the-docs
title: "Nick's Little Project"
description: We are a work in progress!
color_scheme: dark
kramdown:
  math_engine: mathjax
callouts:
  pop:
    color: blue
  theorem:
    title: Theorem
    color: green
  definition:
    title: Definition
    color: blue
  lemma:
    title: Lemma
    color: blue
  corollary:
    title: Corollary
    color: blue