remote_theme: just-the-docs/just-the-docs
title: "Nick's Little Project"
description: We are a work in progress!
color_scheme: dark
kramdown:
  math_engine: mathjax
heading_anchors: false
callouts:
  pop:
    color: blue
  theorem:
    title: Theorem
    color: yellow
  definition:
    title: Definition
    color: green
  proof:
    title: "Proof:"
    color: grey-lt